<div>
    <h2>Publicaciones</h2>
    @include('includes.postPreview')
    @include('includes.postPreview')
    @include('includes.postPreview')
    @include('includes.postPreview')
    @include('includes.postPreview')
    @include('includes.postPreview')
    paginación
</div>
