<div>
    @include('includes.postPreview')
    @include('includes.postPreview')
    @include('includes.postPreview')
    @include('includes.postPreview')
    @include('includes.postPreview')
    @include('includes.postPreview')
    paginación
</div>
